source "http://ruby.taobao.org"

gem "mongoid", "~> 3.1.6"
gem 'mongoid-versioning', github: 'simi/mongoid-versioning'
gem "sinatra"
gem "sinatra-contrib"
gem "pry"
gem "haml"
gem "unicorn"
gem 'sinatra-assetpack'
gem 'sass'
gem 'coffee-script'
gem 'yui-compressor'
gem 'uglifier'
gem 'actionpack', '3.2.12'

gem 'mina',
    :git => 'git://github.com/fushang318/mina.git',
    :tag => 'v0.2.0fix'

group :test do
  gem "rspec"
  gem "database_cleaner", "~> 1.2.0"
end